name: ðŸ§© Detect & Act on File Changes

on:
  workflow_dispatch:

jobs:
  call_reusable:
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/check-file-changes.yml@main
    with:
      watched_files: |
        src/**
        config/**
      base_ref: main
