name: ğŸ§© Detect & Act on File Changes

on:
  workflow_dispatch:

jobs:
  call_reusable:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“ Placeholder step
        run: echo "This step exists to make the workflow appear in the Create workflow tab"
      - name: Call reusable workflow
        uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/check-file-changes.yml@main
        with:
          watched_files: |
            src/**
            config/**
          base_ref: main
